dist: focal
sudo: required
services:
  - docker

install:
  - pip3 install -r requirements.txt

script:
  - pytest --flake8

after_success: 
  - pip3 install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker build -t helloworld .
  - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 681061471394.dkr.ecr.ap-south-1.amazonaws.com
  - docker tag helloworld:latest 681061471394.dkr.ecr.ap-south-1.amazonaws.com/helloworld:latest
  - docker push 681061471394.dkr.ecr.ap-south-1.amazonaws.com/helloworld:latest
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
