dist: xenial
group: edge
stages:
- name: Linting
  if: branch = master AND type = push AND fork = false
jobs:
  include:
  - stage: Linting
    name: Linting app.py
    install:
    - pip install -r requirements.txt
    script:
    - pytest --flake8
