dist: focal
sudo: required
services:
  - docker

install:
  - pip3 install -r requirements.txt

script:
  - pytest --flake8

after_success: 
  - pip3 install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker build -t helloworld .
  - docker tag helloworld:latest 681061471394.dkr.ecr.ap-south-1.amazonaws.com/helloworld:latest
  - aws ecr get-login-password --region ap-south-1 | docker login --username raghavTinker --password-stdin 681061471394.dkr.ecr.ap-south-1.amazonaws.com
  - docker push 681061471394.dkr.ecr.ap-south-1.amazonaws.com/helloworld:latest