dist: focal
sudo: required
services:
  - docker

install:
  - pip3 install -r requirements.txt

script:
  - pytest --flake8

after_success: 
  - pip3 install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t helloworld .
  - docker tag helloworld:latest 681061471394.dkr.ecr.ap-south-1.amazonaws.com/helloworld:latest
  - docker push 681061471394.dkr.ecr.ap-south-1.amazonaws.com/helloworld:latest
